# Default application configuration that all configurations inherit from.
# Documentation: https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md
exclude: ''

linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  MergeableSelector:
    enabled: true

  DuplicateRoot:
    enabled: false

  EmptyLineBetweenBlocks:
    enabled: false
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  Indentation:
    enabled: true
    width: 4

  LeadingZero:
    enabled: true
    style: exclude_zero

  NameFormat:
    enabled: true
    convention: BEM

  PlaceholderInExtend:
    enabled: true

  PropertySortOrder:
    enabled: true

  PropertySpelling:
    enabled: true
    extra_properties: []

  SelectorDepth:
    enabled: true
    max_depth: 4

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: false

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: false

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
